# Site settings
title: Everett Liu's Blog
description: graph world
url: "https://ALex-Everett-Liu.github.io"
baseurl: ""

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  posts:
    output: true

# Sass
sass:
  sass_dir: assets/css

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Permalink style
permalink: date

# Pagination
paginate_path: /page:num

